theme: jekyll-theme-minimal
description: 1-click video calls for your website and products
logo: https://raw.githubusercontent.com/daily-co/daily-js/gh-pages/assets/logo-daily-fullcolor-lightground.svg
